inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.3
  Include:
    - 'Rakefile'
    - 'Gemfile'
    - 'Rakefile'
  Exclude:
    - 'vendor/**/*'
    - 'demo/**/*'

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false